exports.DATABASE_TABLES = {
  USERS: "users",
  ROLES: "roles",
  USER_ROLES: "user_roles",
  PATIENTS: "patients",
  DEPARTMENTS: "departments",
  DOCTORS: "doctors",
  DOCTOR_SLOTS: "doctor_slots",
  APPOINTMENTS: "appointments",
  MEDICAL_SERVICES: "medical_services",
  NEWS_ARTICLES: "news_articles",
  LAB_RESULTS: "lab_results",
  AUTH_SESSIONS: "auth_sessions",
  AUTH_LOGIN_ATTEMPTS: "auth_login_attempts",
  CMS_PAGES: "cms_pages",
  CONTACT_MESSAGES: "contact_messages",
  PRESCRIPTIONS: "prescriptions",
  PAYMENT_TRANSACTIONS: "payment_transactions",
  DOCTOR_REVIEWS: "doctor_reviews",
  NOTIFICATIONS: "notifications",
  NOTIFICATION_JOBS: "notification_jobs",
  MEDICINES: "medicines",
  LAB_TEST_CATALOG: "lab_test_catalog",
  SYSTEM_SETTINGS: "system_settings",
  AUDIT_LOGS: "audit_logs",
};
