const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const admins = require("../controllers/admins");
const admins_validation = require("../utils/validators/admins.validation");
exports.adminPortalRoutes = express.Router();
exports.adminPortalRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.adminPortalRoutes.get("/dashboard/overview", admins.dashboardOverviewController);
exports.adminPortalRoutes.get("/dashboard/trends", admins.dashboardTrendsController);
exports.adminPortalRoutes.get("/users", admins.listUsersController);
exports.adminPortalRoutes.post("/users", validateHandler.validateBody(admins_validation.adminCreateUserSchema), admins.createUserController);
exports.adminPortalRoutes.patch("/users/:userId", validateHandler.validateBody(admins_validation.adminUpdateUserSchema), admins.updateUserController);
exports.adminPortalRoutes.patch("/users/:userId/status", validateHandler.validateBody(admins_validation.adminUpdateUserStatusSchema), admins.updateUserStatusController);
exports.adminPortalRoutes.patch("/users/:userId/roles", validateHandler.validateBody(admins_validation.adminUpdateUserRolesSchema), admins.updateUserRolesController);
exports.adminPortalRoutes.delete("/users/:userId", admins.deleteUserController);
exports.adminPortalRoutes.get("/reports/revenue", admins.revenueReportController);
exports.adminPortalRoutes.get("/reports/revenue/export", admins.revenueExportController);
exports.adminPortalRoutes.get("/reports/advanced/overview", admins.advancedOverviewController);
exports.adminPortalRoutes.get("/reports/advanced/top-departments", admins.topDepartmentsController);
exports.adminPortalRoutes.get("/reports/advanced/revenue-by-service", admins.revenueByServiceController);
exports.adminPortalRoutes.get("/reports/advanced/export", admins.advancedExportController);
exports.adminPortalRoutes.get("/reports/payments/reconciliation", admins.paymentReconciliationController);
exports.adminPortalRoutes.patch("/reports/payments/:paymentId/reconcile", admins.reconcilePaymentController);
exports.adminPortalRoutes.get("/notifications/jobs", admins.listNotificationJobsController);
exports.adminPortalRoutes.post("/notifications/jobs/process", admins.processNotificationJobsController);
exports.adminPortalRoutes.post("/notifications/doctor-announcements", validateHandler.validateBody(admins_validation.adminDoctorAnnouncementSchema), admins.createDoctorAnnouncementController);
exports.adminPortalRoutes.get("/settings", admins.listSettingsController);
exports.adminPortalRoutes.put("/settings", validateHandler.validateBody(admins_validation.adminSettingSchema), admins.upsertSettingController);
exports.adminPortalRoutes.get("/medicines", admins.listMedicinesController);
exports.adminPortalRoutes.post("/medicines", validateHandler.validateBody(admins_validation.medicineSchema), admins.createMedicineController);
exports.adminPortalRoutes.put("/medicines/:medicineId", validateHandler.validateBody(admins_validation.medicineSchema), admins.updateMedicineController);
exports.adminPortalRoutes.delete("/medicines/:medicineId", admins.deleteMedicineController);
exports.adminPortalRoutes.get("/lab-tests", admins.listLabTestCatalogController);
exports.adminPortalRoutes.post("/lab-tests", validateHandler.validateBody(admins_validation.labTestCatalogSchema), admins.createLabTestCatalogController);
exports.adminPortalRoutes.put("/lab-tests/:testId", validateHandler.validateBody(admins_validation.labTestCatalogSchema), admins.updateLabTestCatalogController);
exports.adminPortalRoutes.delete("/lab-tests/:testId", admins.deleteLabTestCatalogController);
