const express_1 = require("express");
const roles_1 = require("../constants/roles");
const authHandler_1 = require("../utils/authHandler");
const validateHandler_1 = require("../utils/validateHandler");
const admins_1 = require("../controllers/admins");
const admins_validation_1 = require("../utils/validators/admins.validation");
exports.adminPortalRoutes = express_1.Router();
exports.adminPortalRoutes.use(authHandler_1.CheckLogin, authHandler_1.CheckRole(roles_1.ROLES.ADMIN));
exports.adminPortalRoutes.get("/dashboard/overview", admins_1.dashboardOverviewController);
exports.adminPortalRoutes.get("/dashboard/trends", admins_1.dashboardTrendsController);
exports.adminPortalRoutes.get("/users", admins_1.listUsersController);
exports.adminPortalRoutes.post("/users", validateHandler_1.validateBody(admins_validation_1.adminCreateUserSchema), admins_1.createUserController);
exports.adminPortalRoutes.patch("/users/:userId", validateHandler_1.validateBody(admins_validation_1.adminUpdateUserSchema), admins_1.updateUserController);
exports.adminPortalRoutes.patch("/users/:userId/status", validateHandler_1.validateBody(admins_validation_1.adminUpdateUserStatusSchema), admins_1.updateUserStatusController);
exports.adminPortalRoutes.patch("/users/:userId/roles", validateHandler_1.validateBody(admins_validation_1.adminUpdateUserRolesSchema), admins_1.updateUserRolesController);
exports.adminPortalRoutes.delete("/users/:userId", admins_1.deleteUserController);
exports.adminPortalRoutes.get("/reports/revenue", admins_1.revenueReportController);
exports.adminPortalRoutes.get("/reports/revenue/export", admins_1.revenueExportController);
exports.adminPortalRoutes.get("/reports/advanced/overview", admins_1.advancedOverviewController);
exports.adminPortalRoutes.get("/reports/advanced/top-departments", admins_1.topDepartmentsController);
exports.adminPortalRoutes.get("/reports/advanced/revenue-by-service", admins_1.revenueByServiceController);
exports.adminPortalRoutes.get("/reports/advanced/export", admins_1.advancedExportController);
exports.adminPortalRoutes.get("/reports/payments/reconciliation", admins_1.paymentReconciliationController);
exports.adminPortalRoutes.patch("/reports/payments/:paymentId/reconcile", admins_1.reconcilePaymentController);
exports.adminPortalRoutes.get("/notifications/jobs", admins_1.listNotificationJobsController);
exports.adminPortalRoutes.post("/notifications/jobs/process", admins_1.processNotificationJobsController);
exports.adminPortalRoutes.get("/settings", admins_1.listSettingsController);
exports.adminPortalRoutes.put("/settings", validateHandler_1.validateBody(admins_validation_1.adminSettingSchema), admins_1.upsertSettingController);
exports.adminPortalRoutes.get("/medicines", admins_1.listMedicinesController);
exports.adminPortalRoutes.post("/medicines", validateHandler_1.validateBody(admins_validation_1.medicineSchema), admins_1.createMedicineController);
exports.adminPortalRoutes.put("/medicines/:medicineId", validateHandler_1.validateBody(admins_validation_1.medicineSchema), admins_1.updateMedicineController);
exports.adminPortalRoutes.delete("/medicines/:medicineId", admins_1.deleteMedicineController);
exports.adminPortalRoutes.get("/lab-tests", admins_1.listLabTestCatalogController);
exports.adminPortalRoutes.post("/lab-tests", validateHandler_1.validateBody(admins_validation_1.labTestCatalogSchema), admins_1.createLabTestCatalogController);
exports.adminPortalRoutes.put("/lab-tests/:testId", validateHandler_1.validateBody(admins_validation_1.labTestCatalogSchema), admins_1.updateLabTestCatalogController);
exports.adminPortalRoutes.delete("/lab-tests/:testId", admins_1.deleteLabTestCatalogController);
