const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const bookings = require("../controllers/bookings");
const bookings_validation = require("../utils/validators/bookings.validation");
exports.bookingsRoutes = express.Router();
exports.bookingsAdminRoutes = express.Router();
exports.bookingsRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.PATIENT));
exports.bookingsRoutes.post("/", validateHandler.validateBody(bookings_validation.bookingBodySchema), bookings.createBookingController);
exports.bookingsRoutes.get("/me", bookings.myBookingsController);
exports.bookingsAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN, roles.ROLES.STAFF));
exports.bookingsAdminRoutes.get("/", bookings.bookingsAdminController);
exports.bookingsAdminRoutes.get("/:bookingId", bookings.bookingDetailAdminController);
exports.bookingsAdminRoutes.patch("/:bookingId/status", validateHandler.validateBody(bookings_validation.bookingStatusSchema), bookings.updateBookingStatusController);
