const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const cms = require("../controllers/cms");
const cms_validation = require("../utils/validators/cms.validation");
exports.cmsRoutes = express.Router();
exports.cmsAdminRoutes = express.Router();
exports.cmsRoutes.get("/pages/:pageKey", cms.cmsPageDetailController);
exports.cmsAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.cmsAdminRoutes.get("/pages", cms.listCmsPagesController);
exports.cmsAdminRoutes.put("/pages/:pageKey", validateHandler.validateBody(cms_validation.cmsPageBodySchema), cms.upsertCmsPageController);
