const express_1 = require("express");
const roles_1 = require("../constants/roles");
const authHandler_1 = require("../utils/authHandler");
const validateHandler_1 = require("../utils/validateHandler");
const contacts_1 = require("../controllers/contacts");
const contacts_validation_1 = require("../utils/validators/contacts.validation");
exports.contactRoutes = express_1.Router();
exports.contactAdminRoutes = express_1.Router();
exports.contactRoutes.post("/messages", validateHandler_1.validateBody(contacts_validation_1.contactBodySchema), contacts_1.createContactMessageController);
exports.contactAdminRoutes.use(authHandler_1.CheckLogin, authHandler_1.CheckRole(roles_1.ROLES.ADMIN, roles_1.ROLES.STAFF));
exports.contactAdminRoutes.get("/messages", contacts_1.listContactMessagesController);
exports.contactAdminRoutes.get("/messages/:messageId", contacts_1.contactMessageDetailController);
