const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const contacts = require("../controllers/contacts");
const contacts_validation = require("../utils/validators/contacts.validation");
exports.contactRoutes = express.Router();
exports.contactAdminRoutes = express.Router();
exports.contactRoutes.post("/messages", validateHandler.validateBody(contacts_validation.contactBodySchema), contacts.createContactMessageController);
exports.contactAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN, roles.ROLES.STAFF));
exports.contactAdminRoutes.get("/messages", contacts.listContactMessagesController);
exports.contactAdminRoutes.get("/messages/:messageId", contacts.contactMessageDetailController);
