const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const departments = require("../controllers/departments");
const departments_validation = require("../utils/validators/departments.validation");
exports.departmentsRoutes = express.Router();
exports.departmentsAdminRoutes = express.Router();
exports.departmentsRoutes.get("/", departments.listDepartmentsController);
exports.departmentsAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.departmentsAdminRoutes.get("/", departments.listDepartmentsAdminController);
exports.departmentsAdminRoutes.post("/", validateHandler.validateBody(departments_validation.departmentBodySchema), departments.createDepartmentController);
exports.departmentsAdminRoutes.put("/:departmentId", validateHandler.validateBody(departments_validation.departmentBodySchema), departments.updateDepartmentController);
exports.departmentsAdminRoutes.delete("/:departmentId", departments.deleteDepartmentController);
