const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const doctors = require("../controllers/doctors");
const doctors_validation = require("../utils/validators/doctors.validation");
exports.doctorsRoutes = express.Router();
exports.doctorsAdminRoutes = express.Router();
exports.doctorsRoutes.get("/", doctors.listDoctorsController);
exports.doctorsRoutes.get("/:doctorId/slots", doctors.listDoctorSlotsController);
exports.doctorsAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.doctorsAdminRoutes.get("/", doctors.listDoctorsAdminController);
exports.doctorsAdminRoutes.post("/", validateHandler.validateBody(doctors_validation.doctorBodySchema), doctors.createDoctorController);
exports.doctorsAdminRoutes.put("/:doctorId", validateHandler.validateBody(doctors_validation.doctorBodySchema), doctors.updateDoctorController);
exports.doctorsAdminRoutes.delete("/:doctorId", doctors.deleteDoctorController);
exports.doctorsAdminRoutes.post("/slots", validateHandler.validateBody(doctors_validation.doctorSlotBodySchema), doctors.createDoctorSlotController);
exports.doctorsAdminRoutes.delete("/slots/:slotId", doctors.deleteDoctorSlotController);
