const express_1 = require("express");
const admins_1 = require("./admins");
const auths_1 = require("./auths");
const bookings_1 = require("./bookings");
const cms_1 = require("./cms");
const contacts_1 = require("./contacts");
const departments_1 = require("./departments");
const doctor_profiles_1 = require("./doctor-profiles");
const doctors_1 = require("./doctors");
const lab_results_1 = require("./lab-results");
const news_1 = require("./news");
const patients_1 = require("./patients");
const recruitment_applications_1 = require("./recruitment-applications");
const rss_1 = require("./rss");
const services_1 = require("./services");
exports.router = express_1.Router();
exports.router.use("/auth", auths_1.authRoutes);
exports.router.use("/departments", departments_1.departmentsRoutes);
exports.router.use("/doctors", doctors_1.doctorsRoutes);
exports.router.use("/services", services_1.servicesRoutes);
exports.router.use("/news", news_1.newsRoutes);
exports.router.use("/bookings", bookings_1.bookingsRoutes);
exports.router.use("/lab-results", lab_results_1.labResultsRoutes);
exports.router.use("/contacts", contacts_1.contactRoutes);
exports.router.use("/contact", contacts_1.contactRoutes);
exports.router.use("/cms", cms_1.cmsRoutes);
exports.router.use("/rss", rss_1.rssRoutes);
exports.router.use("/rss-news", rss_1.rssRoutes);
exports.router.use("/recruitment-applications", recruitment_applications_1.recruitmentRoutes);
exports.router.use("/patients", patients_1.patientRoutes);
exports.router.use("/patient", patients_1.patientRoutes);
exports.router.use("/doctors/me", doctor_profiles_1.doctorRoutes);
exports.router.use("/doctor", doctor_profiles_1.doctorRoutes);
exports.router.use("/admin/portal", admins_1.adminPortalRoutes);
exports.router.use("/admin/departments", departments_1.departmentsAdminRoutes);
exports.router.use("/admin/doctors", doctors_1.doctorsAdminRoutes);
exports.router.use("/admin/services", services_1.servicesAdminRoutes);
exports.router.use("/admin/news", news_1.newsAdminRoutes);
exports.router.use("/admin/bookings", bookings_1.bookingsAdminRoutes);
exports.router.use("/admin/lab-results", lab_results_1.labResultsAdminRoutes);
exports.router.use("/admin/contacts", contacts_1.contactAdminRoutes);
exports.router.use("/admin/contact", contacts_1.contactAdminRoutes);
exports.router.use("/admin/cms", cms_1.cmsAdminRoutes);
exports.router.use("/admin/recruitment-applications", recruitment_applications_1.recruitmentAdminRoutes);
