const express = require("express");
const admins = require("./admins");
const auths = require("./auths");
const bookings = require("./bookings");
const cms = require("./cms");
const contacts = require("./contacts");
const departments = require("./departments");
const doctor_profiles = require("./doctor-profiles");
const doctors = require("./doctors");
const lab_results = require("./lab-results");
const news = require("./news");
const patient_records = require("./patient-records");
const patients = require("./patients");
const recruitment_applications = require("./recruitment-applications");
const rss = require("./rss");
const services = require("./services");
exports.router = express.Router();
exports.router.use("/auth", auths.authRoutes);
exports.router.use("/departments", departments.departmentsRoutes);
exports.router.use("/doctors", doctors.doctorsRoutes);
exports.router.use("/services", services.servicesRoutes);
exports.router.use("/news", news.newsRoutes);
exports.router.use("/bookings", bookings.bookingsRoutes);
exports.router.use("/lab-results", lab_results.labResultsRoutes);
exports.router.use("/patient-records", patient_records.patientRecordsRoutes);
exports.router.use("/medical-records", patient_records.patientRecordsRoutes);
exports.router.use("/contacts", contacts.contactRoutes);
exports.router.use("/contact", contacts.contactRoutes);
exports.router.use("/cms", cms.cmsRoutes);
exports.router.use("/rss", rss.rssRoutes);
exports.router.use("/rss-news", rss.rssRoutes);
exports.router.use("/recruitment-applications", recruitment_applications.recruitmentRoutes);
exports.router.use("/patients", patients.patientRoutes);
exports.router.use("/patient", patients.patientRoutes);
exports.router.use("/doctors/me", doctor_profiles.doctorRoutes);
exports.router.use("/doctor", doctor_profiles.doctorRoutes);
exports.router.use("/admin/portal", admins.adminPortalRoutes);
exports.router.use("/admin/departments", departments.departmentsAdminRoutes);
exports.router.use("/admin/doctors", doctors.doctorsAdminRoutes);
exports.router.use("/admin/services", services.servicesAdminRoutes);
exports.router.use("/admin/news", news.newsAdminRoutes);
exports.router.use("/admin/bookings", bookings.bookingsAdminRoutes);
exports.router.use("/admin/lab-results", lab_results.labResultsAdminRoutes);
exports.router.use("/admin/contacts", contacts.contactAdminRoutes);
exports.router.use("/admin/contact", contacts.contactAdminRoutes);
exports.router.use("/admin/cms", cms.cmsAdminRoutes);
exports.router.use("/admin/recruitment-applications", recruitment_applications.recruitmentAdminRoutes);
