const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const news = require("../controllers/news");
const news_validation = require("../utils/validators/news.validation");
exports.newsRoutes = express.Router();
exports.newsAdminRoutes = express.Router();
exports.newsRoutes.get("/", news.listNewsController);
exports.newsRoutes.get("/:slug", news.getNewsDetailController);
exports.newsAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.newsAdminRoutes.get("/", news.listNewsAdminController);
exports.newsAdminRoutes.post("/", validateHandler.validateBody(news_validation.newsBodySchema), news.createNewsController);
exports.newsAdminRoutes.put("/:newsId", validateHandler.validateBody(news_validation.newsBodySchema), news.updateNewsController);
exports.newsAdminRoutes.delete("/:newsId", news.deleteNewsController);
