const express = require("express");
const roles = require("../constants/roles");
const authHandler = require("../utils/authHandler");
const validateHandler = require("../utils/validateHandler");
const services = require("../controllers/services");
const services_validation = require("../utils/validators/services.validation");
exports.servicesRoutes = express.Router();
exports.servicesAdminRoutes = express.Router();
exports.servicesRoutes.get("/", services.listServicesController);
exports.servicesAdminRoutes.use(authHandler.CheckLogin, authHandler.CheckRole(roles.ROLES.ADMIN));
exports.servicesAdminRoutes.get("/", services.listServicesAdminController);
exports.servicesAdminRoutes.post("/", validateHandler.validateBody(services_validation.serviceBodySchema), services.createServiceController);
exports.servicesAdminRoutes.put("/:serviceId", validateHandler.validateBody(services_validation.serviceBodySchema), services.updateServiceController);
exports.servicesAdminRoutes.delete("/:serviceId", services.deleteServiceController);
